[connections.mysql]
dialect = "mysql"
driver = "pymysql"
database = "archery_db"
username = "root"
password = ""
host = "localhost"
port = 3306

[google_ai]
api_key = "AIzaSyBbweld2NZVrsWjNGREaek5IHdOi8C6yEs"